env:
  - CXX=g++-5.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5.1
language: node_js
node_js:
  - "4.2"
  - "5.4"
  - 6
  - 7
sudo: false
script:
  # Run test script, depending on istanbul install
  - "test ! -z $(npm -ps ls istanbul) || npm test"
  - "test   -z $(npm -ps ls istanbul) || npm run-script test-travis"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
