language: node_js
sudo: false
node_js:
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4

#env:
#  global:
#    - CXX=g++-5
#
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-5

cache:
  directories:
    - node_modules

script: npm test
after_success: cat ./coverage/lcov.info | coveralls
