language: node_js
sudo: false

stages:
  - Test
  - name: Deploy
    if: tag IS present

cache:
  directories:
    - node_modules
before_cache: rm -rf node_modules/.cache

stdJob: &stdJob
  stage: Test
  before_script: greenkeeper-lockfile-update
  script:
    - if [ $SNYK_TOKEN ]; then snyk test --dev; fi;
    - npm test
  after_success: cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - node_js: &node_latest 9
      <<: *stdJob
      after_script:
        - if [ $GH_TOKEN ]; then greenkeeper-lockfile-upload; fi;
        - if [ $SNYK_TOKEN ]; then snyk monitor --dev; fi;
    - node_js: 8
      <<: *stdJob
    - node_js: 7
      <<: *stdJob
    - node_js: 6
      <<: *stdJob
    - node_js: 5
      <<: *stdJob
    - node_js: 4
      <<: *stdJob
    - stage: Deploy
      node_js: *node_latest
      script: true
      before_deploy: node ./prepublish.js
      deploy:
        - provider: npm
          on:
            tags: true
          email: a.molcanovas@gmail.com
          api_key:
            secure: "hpUbX+WiGGaN95yyBK2McFxrPAVl9WnRhd7tuQGvUDnclepIP1k5jPmWrrQouMNSvSYWyRFphMSgl997qsqebBJRRLlJehcow7lN1KbmWO+/UUWwfxpH49kQhtMO+l6fuZg0iU51cB55MuP9JFLhTset/6rn4MVdkF0+dHfIDR59vkgo9gHB9M9+fcFNATfzS0zRmO15xDP4M3VD2JsyhAa612hJU9YbRURaRGmaJG4XgQzbfS7sp0ltYeHybKvqP8t6yDnjRhDLSE3Zo2sy2WtXjSvgM2Gom3iNKdRAz2GBm8GOG+E1TaKxonQXJTFIFsBHw/F5a5u9rgf+Hlx+Z5k5mNxthVgBNDGKBuBh0nMewd5D9y5nw+AjoOHDMcaplbx0rKGpb2waYAcRcJkIl4UHZEUyY/A7scBc4CuFWwqAo/FoClFOBpDU+PeIk+3Wqbf1ax5jNgLIu5NYj/Utfa9kUOZ7sLw6E1jwfxMSVOtCDieWYsOUjzixUzU2ZJtpDSIilvaOfVdV0AKqjIuXoQM0ex5Tt8brnBaMcHPvsUr7TCqFfdEVjjQ7chNUqoJKPwvBnRqP2ji0Ly/BaVGXo3pq9JqRB0KAI7yTn1WSZeNF0rVOMnfhxBdU21eWZCJn+BCl0ZLl9mGUZetQuxEznqW6ytNc7Zz6C9APW4GEh5c="
