language: node_js
sudo: false
node_js:
  - stable
  - lts/boron
  - lts/carbon

cache:
  directories:
    - node_modules
before_cache: rm -rf node_modules/.cache
install: npm install --build-from-source
after_success: cat ./coverage/lcov.info | coveralls

stages:
  - test
  - name: Deploy
    if: tag IS present

jobs:
  include:
    - stage: Deploy
      node_js: stable
      script: node ./prepublish.js
      after_success: false
      deploy:
        - provider: npm
          skip_cleanup: true
          on:
            tags: true
          email: a.molcanovas@gmail.com
          api_key:
            secure: eyBRP3S2d0cw9ilHrG4STfz6fpEAqU4kttkJJJIMrHAu5/dFFqJGPulbK8f+172LhR/Ix56/UGAz8X2mI3OEbszgEhvffcxb7vUvCb7cnjcEUueblIH/YeQWD/yG4D98tN8V59oKgpfC4nxLbMlM97E3F+9caJbuJnLgjckM4hsthJRdfs1xtzj+A+wcbI1efWTS75BUEKvhL151Q5rfKL5fiOADZlwrW0dTqBIYunthrbZ+aa84nT2jHxlaSG8E+IN7LCnXiZNtFOKnkYOdoOpYMBsbVP7RHl1XdxHR1a/QloogWavZlF17p3KSd2uYbOAKxc7gWa0nWB9XeLCrb4/MXOey7u6dxos8ChcmacEcnkQ0PaH13J3TTB+80soanINN11/QwWH/ZKwjH30FYzy/C3LeLkF01kW/u38hY8iNE3Ysh2h1M+bdWrfJykGMVaZnAGV3zOXQEZBUNvyBzR0QDkeBDKWEPvMglmtKlhCCVU0rvTmrx+r/t/6Je/zeOPlZS3ZxmLv2v6bHVPWNxaHxAmdcDGlyYzLXVPVpx6sAOu9ILPquVIm0FBQBDmtnj6h103a67ta+uRx1cnsYgTWdv9B1ubXUXbxLzsrilukeZvfWTJE8oDDaR1WSevXiAahkkTek1R8ooiTBOP0CCExu747tbIg0NCN7GtA8Fm0=
