language: node_js
sudo: false
node_js:
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4

cache:
  directories:
    - node_modules

before_cache: rm -rf node_modules/.cache

script: npm test
after_success: cat ./coverage/lcov.info | coveralls
