language: node_js
sudo: false

stages:
  - Test
  - name: Deploy
    if: tag IS present

cache:
  directories:
    - node_modules
before_cache: rm -rf node_modules/.cache

stdJob: &stdJob
  stage: Test
  script: npm test
  after_success: cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - node_js: &node_latest 9
      <<: *stdJob
    - node_js: 8
      <<: *stdJob
    - node_js: 7
      <<: *stdJob
    - node_js: 6
      <<: *stdJob
    - node_js: '6.0'
      <<: *stdJob
    - stage: Deploy
      node_js: *node_latest
      script: node ./prepublish.js
      deploy:
        - provider: npm
          skip_cleanup: true
          on:
            tags: true
          email: a.molcanovas@gmail.com
          api_key:
            secure: ESFC7zrBktlkcECaF3ORg1/lXJ9Z6hkG280bgWzJP6dWJ3Cb0LO1ZCj5gn8VSBNer5WQSMM64YbqP/0yCcgXK4vJZ+Kb2JeolEfuK6vkhkRqrNK+G8h8FZbuHXdx62et+lSoAYFhxQVhX2pkR7GUAC9Vr3dJcQ36MieknYiD97DxvwyFN3qYbe3y59A7N2ypU9sqF35Mwp5XDLox30+9h5ChGl+Q23EBFfb8YiZZ6S6ncAczLkae3AY+j/fxW1fOP6xaCEyUNWAoq6UOYTn5BqlkGBcg89RldJsxE43VvRiOpnXrFF+FJxAhYcHb91/hJdC+LmyMl/y9w0sYdWahZxqwNP+Xpt/wj47B7Z5hSKJRUg6X4CnHeJSV2U6uoBHs24ykpr1+/9+8pXkOReHtvD5uxjlq5iO7b8FgI4MeGsz84qSaFFXHIAPss9QkXT+fiadLh2tbeTzBLfE5GrF7TnMRD3Ouz5RxginMQhgRuCccgVqhElFnQJIeDVFw4uQ44f0/omPqWWCoBK5DairU/k5zUAZocKHRNS3DCjOA+jzclfDJoZaFiSAivfHFji+1b6J0kamtVxd8Sqjfttnql6Z2nZ+c33tJ6Vh8psbz40QSvW2I+e7OMLcGcQeekXfw1iJSyeCPcrahY6h5IEsUxlBJSlH/zeiiMBoJCUJ7GV0=
